import { DollarSign, Users, Target, TrendingUp, Smartphone, Zap, Package, Palette, BarChart3 } from "lucide-react"

export const kpis = [
  {
    title: "Revenue",
    value: "$2.4M",
    change: 12.5,
    icon: DollarSign,
  },
  {
    title: "Active Projects",
    value: "23",
    change: 8.2,
    icon: Target,
  },
  {
    title: "Team Members",
    value: "127",
    change: 5.1,
    icon: Users,
  },
  {
    title: "Market Share",
    value: "18.3%",
    change: -2.1,
    icon: TrendingUp,
  },
]

export const recentInitiatives = [
  {
    id: 1,
    title: "Wireless Charging Ecosystem",
    department: "Product Development",
    progress: 75,
    status: "On Track",
    dueDate: "Q2 2024",
  },
  {
    id: 2,
    title: "Sustainable Materials Integration",
    department: "Design",
    progress: 45,
    status: "At Risk",
    dueDate: "Q3 2024",
  },
  {
    id: 3,
    title: "European Market Expansion",
    department: "Sales",
    progress: 90,
    status: "On Track",
    dueDate: "Q1 2024",
  },
]

export const upcomingMilestones = [
  {
    id: 1,
    title: "Q1 Product Launch",
    date: "Mar 15",
    department: "Product",
  },
  {
    id: 2,
    title: "Design Review Meeting",
    date: "Mar 20",
    department: "Design",
  },
  {
    id: 3,
    title: "Investor Presentation",
    date: "Mar 25",
    department: "Executive",
  },
  {
    id: 4,
    title: "Team All-Hands",
    date: "Apr 1",
    department: "HR",
  },
]

export const allInitiatives = [
  {
    id: 1,
    title: "Wireless Charging Ecosystem",
    description: "Develop a comprehensive wireless charging solution for all Native Union products",
    department: "Product Development",
    progress: 75,
    status: "On Track",
    dueDate: "Q2 2024",
    owner: "Sarah Chen",
    budget: 450000,
  },
  {
    id: 2,
    title: "Sustainable Materials Integration",
    description: "Transition 80% of product line to sustainable and recycled materials",
    department: "Design",
    progress: 45,
    status: "At Risk",
    dueDate: "Q3 2024",
    owner: "Marcus Rodriguez",
    budget: 320000,
  },
  {
    id: 3,
    title: "European Market Expansion",
    description: "Launch Native Union products in 5 new European markets",
    department: "Sales",
    progress: 90,
    status: "On Track",
    dueDate: "Q1 2024",
    owner: "Emma Thompson",
    budget: 280000,
  },
  {
    id: 4,
    title: "AI-Powered Customer Support",
    description: "Implement AI chatbot and automated support system",
    department: "Technology",
    progress: 30,
    status: "Planning",
    dueDate: "Q4 2024",
    owner: "David Kim",
    budget: 180000,
  },
  {
    id: 5,
    title: "Premium Audio Line",
    description: "Launch high-end audio accessories targeting audiophile market",
    department: "Product Development",
    progress: 60,
    status: "On Track",
    dueDate: "Q3 2024",
    owner: "Lisa Park",
    budget: 520000,
  },
]

export const projects = [
  {
    id: 1,
    name: "MagSafe Ecosystem V2",
    description: "Next generation MagSafe compatible accessories",
    department: "Product Development",
    status: "In Progress",
    progress: 68,
    dueDate: "Apr 30, 2024",
    teamSize: 8,
    budget: 340000,
    manager: {
      name: "Sarah Chen",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  },
  {
    id: 2,
    name: "Sustainable Packaging",
    description: "Eco-friendly packaging redesign for all products",
    department: "Design",
    status: "In Progress",
    progress: 42,
    dueDate: "Jun 15, 2024",
    teamSize: 5,
    budget: 125000,
    manager: {
      name: "Marcus Rodriguez",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  },
  {
    id: 3,
    name: "Retail Partnership Program",
    description: "Expand retail presence in premium electronics stores",
    department: "Sales",
    status: "Completed",
    progress: 100,
    dueDate: "Feb 28, 2024",
    teamSize: 6,
    budget: 180000,
    manager: {
      name: "Emma Thompson",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  },
  {
    id: 4,
    name: "Mobile App Redesign",
    description: "Complete overhaul of Native Union mobile application",
    department: "Technology",
    status: "In Progress",
    progress: 25,
    dueDate: "Aug 30, 2024",
    teamSize: 12,
    budget: 220000,
    manager: {
      name: "David Kim",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  },
  {
    id: 5,
    name: "Quality Assurance Automation",
    description: "Automated testing system for product quality control",
    department: "Operations",
    status: "Overdue",
    progress: 80,
    dueDate: "Mar 1, 2024",
    teamSize: 4,
    budget: 95000,
    manager: {
      name: "Jennifer Walsh",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  },
  {
    id: 6,
    name: "Brand Refresh Campaign",
    description: "Comprehensive brand identity and marketing campaign update",
    department: "Marketing",
    status: "In Progress",
    progress: 55,
    dueDate: "May 20, 2024",
    teamSize: 9,
    budget: 380000,
    manager: {
      name: "Alex Johnson",
      avatar: "/placeholder.svg?height=32&width=32",
    },
  },
]

export const departments = [
  {
    id: 1,
    name: "Product Development",
    description: "Innovation and product design",
    icon: Smartphone,
    teamSize: 24,
    activeProjects: 8,
    budgetUtilization: 78,
    budgetUsed: 890000,
    totalBudget: 1140000,
    performanceScore: 92,
    head: "Sarah Chen",
    keyInitiatives: [
      { name: "Wireless Charging Ecosystem", status: "On Track" },
      { name: "Premium Audio Line", status: "On Track" },
      { name: "MagSafe V2", status: "In Progress" },
    ],
  },
  {
    id: 2,
    name: "Design",
    description: "Industrial design and user experience",
    icon: Palette,
    teamSize: 16,
    activeProjects: 5,
    budgetUtilization: 65,
    budgetUsed: 420000,
    totalBudget: 645000,
    performanceScore: 85,
    head: "Marcus Rodriguez",
    keyInitiatives: [
      { name: "Sustainable Materials", status: "At Risk" },
      { name: "Packaging Redesign", status: "On Track" },
      { name: "Brand Guidelines", status: "Completed" },
    ],
  },
  {
    id: 3,
    name: "Sales & Marketing",
    description: "Revenue generation and brand promotion",
    icon: TrendingUp,
    teamSize: 18,
    activeProjects: 6,
    budgetUtilization: 82,
    budgetUsed: 720000,
    totalBudget: 880000,
    performanceScore: 88,
    head: "Emma Thompson",
    keyInitiatives: [
      { name: "European Expansion", status: "On Track" },
      { name: "Retail Partnerships", status: "Completed" },
      { name: "Digital Marketing", status: "On Track" },
    ],
  },
  {
    id: 4,
    name: "Technology",
    description: "Software development and IT infrastructure",
    icon: Zap,
    teamSize: 14,
    activeProjects: 4,
    budgetUtilization: 71,
    budgetUsed: 380000,
    totalBudget: 535000,
    performanceScore: 79,
    head: "David Kim",
    keyInitiatives: [
      { name: "AI Customer Support", status: "Planning" },
      { name: "Mobile App Redesign", status: "In Progress" },
      { name: "Cloud Migration", status: "On Track" },
    ],
  },
  {
    id: 5,
    name: "Operations",
    description: "Manufacturing and supply chain management",
    icon: Package,
    teamSize: 32,
    activeProjects: 7,
    budgetUtilization: 89,
    budgetUsed: 1240000,
    totalBudget: 1390000,
    performanceScore: 94,
    head: "Jennifer Walsh",
    keyInitiatives: [
      { name: "Quality Automation", status: "At Risk" },
      { name: "Supply Chain Optimization", status: "On Track" },
      { name: "Inventory Management", status: "Completed" },
    ],
  },
  {
    id: 6,
    name: "Finance & Analytics",
    description: "Financial planning and business intelligence",
    icon: BarChart3,
    teamSize: 8,
    activeProjects: 3,
    budgetUtilization: 58,
    budgetUsed: 180000,
    totalBudget: 310000,
    performanceScore: 91,
    head: "Robert Chen",
    keyInitiatives: [
      { name: "Financial Forecasting", status: "On Track" },
      { name: "Cost Optimization", status: "On Track" },
      { name: "Performance Analytics", status: "Completed" },
    ],
  },
]
